bitacora/urls.py
from django.urls import path
from bitacora.views import *

app_name = 'envios'

urlpatterns = [
    path('', EnvioListView.as_view(), name='envios'),
    path('create/', EnviosCreateView.as_view(), name='envios_create'),
    path('<pk>/', EnviosDetail.as_view(), name='envios_detail'),
    path('<pk>/update/', EnviosUpdateView.as_view(), name='envios_update'),
    path('<pk>/delete/', EnviosDeleteView.as_view(), name='envios_delete'),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('empresa.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('produccion/', include('produccion.urls')),
    path('envios/', include('bitacora.urls')),
    path('almacen/', include('almacen.urls')),
    #Autentificacion
    path('accounts/login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
]

templates/envios/create.html
{% extends "index.html" %}
{% block title %}Envios{% endblock title %}

{% block content %}

<form method="post" role="form" enctype="multipart/form-data" action="">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Enviar">
</form>

<li><a href="{% url 'envios:envios' %}">envios</a></li>

{% endblock %}

templates/envios/delete.html
{% extends "index.html" %}
{% block title %}Envios{% endblock title %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Desea Borrar la Orden de Envios-  "{{ object }}"?</p>
        <input type="submit" value="Eliminar">
 </form>

 <a href="{% url 'envios:envios' %}">
    Cancel
  </a>

  
{% endblock %}

templates/envios/detail.html
{% extends "index.html" %}
{% block title %}Envios{% endblock title %}

{% block content %}

<h2>envios {{object}}</h2>
<h4>
    <br>envios No - {{object.id}}
    <br>Orden de Produccion - {{object.OProduct}}
    <br>Costo de Placas - {{object.CostoPlacas}}
    <br>Total de Placas - {{object.TotalPlacas}}
    <br>Foto envios <img src="{{inicio}}/{{object.Fotoenvios}}" alt="">
    <br>Fecha de preparacion - {{object.FechaPreparacion}}
    <br>Fecha de preparacion Placas - {{object.FechaPlacas}}
    <br>Fecha de Envio Placas - {{object.FechaPlacas}}
    <br>observaciones - {{object.FechaEnvioPlacas}}

    <li><a href="{% url 'envios:envios' %}">envios</a></li>
</h4>

{% endblock %}

templates/envios/list.html
{% extends "index.html" %}
{% block title %}Envios{% endblock title %}

{% block content %}

<h3> Tambien puede Crear un  <a href={% url 'envios:envios_create' %}>Nueva Orde de envios</a> </h3>


{% for envios in EnvioList %}

<p>
    <li> {{ envios.id }}</li>
    <li> {{ envios.RegEntrada }}</li>
    <li> {{ envios.Cliente }}</li>
    <li> <a href="{% url 'envios:envios_detail' envios.id %}">Ver Orden de envios</a></li>
    <li> <a href="{% url 'envios:envios_update' envios.id %}">Editar Orden de envios</a></li>
    <li> <a href="{% url 'envios:envios_delete' envios.id %}">ELIMINAR orden de envios</a></li>
    {% empty %}
    <li>Sin Datos</li>
</p>

{% endfor %}

{% endblock %}

templates/envios/update.html
{% extends "index.html" %}
{% block title %}Envios{% endblock title %}

{% block content %}

<form method="post" role="form" enctype="multipart/form-data" action="">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Enviar">
</form>

<li><a href="{% url 'envios:envios' %}">envios</a></li>

{% endblock %}