produccion/urls.py
from django.urls import path
from produccion.views import *

app_name = 'produccion'

urlpatterns = [
    path('', ProduccionListVIew.as_view(), name='produccion'),
    path('create/', ProduccionCreateView.as_view(), name='produccion_create'),
    path('<pk>/', ProduccionDetail.as_view(), name='produccion_detail'),
    path('<pk>/update/', ProducccionUpdateView.as_view(), name='produccion_update'),
    path('<pk>/delete/', ModelDeleteView.as_view(), name='produccion_delete'),
    
]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('empresa.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('produccion/', include('produccion.urls')),
    path('envios/', include('bitacora.urls')),
    path('almacen/', include('almacen.urls')),
    #Autentificacion
    path('accounts/login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
]

produccion/models.py
from django.db import models
from django.contrib.auth.models import User
from pedidos.models import OPedido
from cliente.models import perfil
from almacen.models import *

# Create your models here.
class OrdenProduccion(models.Model):
    Tipo_Trabajo =(
        ('Nuevo','Nuevo'),
        ('Resurtido','Resurtido'),
        ('Reposición','Reposición'),
    )
    Grosor =(
        ('Sencillo','Sencillo'),
        ('Empalamado','Empalamado'),
        ('Doble Vista','Doble Vista'),
    )
    Folio = models.CharField(verbose_name='Folio de Producción No', max_length=15)
    FolioCliente = models.CharField(verbose_name='Folio de Cliente', max_length=10)
    Cliente = models.ForeignKey(perfil, related_name='Cliente',verbose_name='Cliente', on_delete=models.CASCADE)
    NombreTrabajo = models.CharField(verbose_name='Nombre del Trabajo', max_length=250)
    FechaElaboracion = models.DateField(verbose_name='Fecha de Elaboración', auto_now=False, auto_now_add=False)
    TipoTrabajo = models.CharField(verbose_name='Tipo de Orde',choices=Tipo_Trabajo, max_length=15)
    ImpresionFrente = models.ManyToManyField(Tinta, verbose_name='Tintas Frente', related_name='ImpresionFrente', blank=True)
    ImpresionReverso = models.ManyToManyField(Tinta, verbose_name='Tintas Reverso', related_name='ImpresionReverso', blank=True)
    TipoGrosor = models.CharField(verbose_name='Tipo de Orde',choices=Grosor, max_length=15)
    TipoBarniz = models.ForeignKey(Barniz, verbose_name='Tipo de barniz', on_delete=models.CASCADE, related_name='TipoBarniz', null=True, blank=True)
    TipoLaminado = models.ForeignKey(Laminado, verbose_name='Tipo de Laminado', on_delete=models.CASCADE, related_name='TipoLaminado', null=True, blank=True)
    TipoClisse = models.ForeignKey(Clisse, verbose_name='Tipo de Clisse', on_delete=models.CASCADE, related_name='TipoClisse', null=True, blank=True)
    HotStamping = models.ForeignKey(Foil, verbose_name='Hot Stamping', on_delete=models.CASCADE, related_name='HotStamping', null=True, blank=True)
    TipoBotado = models.ForeignKey(Laser, verbose_name='Botado', on_delete=models.CASCADE, related_name='Botado', null=True, blank=True)
    TipoSuaje = models.ForeignKey(Suaje, verbose_name='Suaje', on_delete=models.CASCADE, related_name='Suaje')
    TipoPapel = models.ForeignKey(Papel, verbose_name='Papel', on_delete=models.CASCADE, related_name='Papel')
    CantidadPapel = models.SmallIntegerField(verbose_name='Tamaños Asignados')
    CantidadMerma = models.SmallIntegerField(verbose_name='Merma Asignada')
    OrdenPedido = models.ForeignKey(OPedido, verbose_name='Pedido Original', on_delete=models.CASCADE, related_name='Orden_Pedido')
    PedidoCantidad = models.PositiveIntegerField(verbose_name='Cantidad Solicitada')
    Observaciones = models.TextField(verbose_name='Observaciones', null=True, blank=True)
    ElaboradoPor = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Elaborado Por:')

    def totalpapel(self):
        resultado = self.CantidadPapel + self.CantidadMerma
        return resultado

    def numgrosor(self):
        if (self.TipoGrosor == 'Empalamado'):
            return 2
        else:
            return 1
    
    def pzas_suaje(self):
        pzas = self.TipoSuaje.CantEtiqueta
        return pzas

    def __str__(self):
        return '{} • {}-{} - {} • {}' .format(self.Folio, self.FolioCliente, self.Cliente, self.NombreTrabajo, self.PedidoCantidad)

    class Meta:
        db_table = 'OrdenProduccion'
        managed = True
        verbose_name = 'OrdenProduccion'
        verbose_name_plural = 'OrdenProduccions'

produccion/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from produccion.models import OrdenProduccion
from django.contrib.auth.mixins import PermissionRequiredMixin
from empresa.models import Empresa


# Create your views here.
class ProduccionListVIew(PermissionRequiredMixin, ListView):
    model = OrdenProduccion
    context_object_name = 'ProduccionList'
    template_name='produccion/list.html'
    paginate_by = 9
    ordering = ['-id']
    permission_required = 'produccion.view_ordenproduccion'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.all()
        return context

class ProduccionDetail(PermissionRequiredMixin, DetailView):
    model = OrdenProduccion
    template_name='produccion/detail.html'
    permission_required = 'produccion.view_ordenproduccion'

class ProduccionCreateView(PermissionRequiredMixin, CreateView):
    model = OrdenProduccion
    template_name = "produccion/create.html"
    fields = '__all__'
    success_url = reverse_lazy('produccion:produccion')
    permission_required = ('produccion.view_ordenproduccion', 'produccion.add_ordenproduccion')

class ProducccionUpdateView(PermissionRequiredMixin, UpdateView):
    model = OrdenProduccion
    template_name = "produccion/update.html"
    fields = '__all__'
    success_url = reverse_lazy('produccion:produccion')
    permission_required = ('produccion.view_ordenproduccion', 'produccion.add_ordenproduccion')

class ModelDeleteView(PermissionRequiredMixin, DeleteView):
    model = OrdenProduccion
    template_name = "produccion/delete.html"
    fields = '__all__'
    success_url = reverse_lazy('produccion:produccion')
    permission_required = ('produccion.view_ordenproduccion', 'produccion.delete_ordenproduccion')

templates/produccion/create.html
{% extends "index.html" %}
{% block title %}Produccion{% endblock title %}

{% block content %}

<form method="post" role="form" enctype="multipart/form-data" action="">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Enviar">
</form>

<li><a href="{% url 'produccion:produccion' %}">produccion</a></li>
{% endblock %}

templates/produccion/delete.html
{% extends "index.html" %}
{% block title %}Produccion{% endblock title %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Desea Borrar la Orden de Produccion-  "{{ object }}"?</p>
        <input type="submit" value="Eliminar">
 </form>

 <a href="{% url 'produccion:produccion' %}">
    Cancel
  </a>

  {% endblock %}

templates/produccion/detail.html
{% extends "index.html" %}
{% block title %}Produccion{% endblock title %}

{% block content %}

<h2>Pedido {{object}}</h2>
<h4>
    <br>Folio No - {{object.Folio}}
    <br>Cliente - {{object.FolioCliente}}
    <br>Nombre del Cliente - {{object.Cliente}}
    <br>Nombre del Trabajo - {{object.NombreTrabajo}}
    <br>Foto Pedido <img src="{{inicio}}/{{object.FotoPedido}}" alt="">
    <br>Fecha de pedido - {{object.FechaPed}}
    <br>Fecha de Elaboracion - {{object.FechaElaboracion}}
    <br>observaciones - {{object.Indicaciones}}
    <li><a href="{% url 'produccion:produccion' %}">produccion</a></li>
</h4>

{% endblock %}

templates/produccion/list.html
{% extends "index.html" %}
{% block title %}Produccion{% endblock title %}

{% block content %}

<h3> Tambien puede Crear un  <a href={% url 'produccion:produccion_create' %}>Nueva Orde de produccion</a> </h3>


{% for produccion in ProduccionList %}

<p>
    <li> {{ produccion.id }}</li>
    <li> {{ produccion.NombreTrabajo }}</li>
    <li> {{ produccion.Cliente }}</li>
    <li> {{ produccion.PedidoCantidad }}</li>
    <li> <a href="{% url 'produccion:produccion_detail' produccion.id %}">Ver Orden de produccion</a></li>
    <li> <a href="{% url 'produccion:produccion_update' produccion.id %}">Editar Orden de produccion</a></li>
    <li> <a href="{% url 'produccion:produccion_delete' produccion.id %}">ELIMINAR orden de produccion</a></li>
    {% empty %}
    <li>Sin Datos</li>
</p>

{% endfor %}

{% endblock %}

templates/produccion/update.html
{% extends "index.html" %}
{% block title %}Produccion{% endblock title %}

{% block content %}

<form method="post" role="form" enctype="multipart/form-data" action="">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Enviar">
</form>

<li><a href="{% url 'produccion:produccion' %}">produccion</a></li>

{% endblock %}